services:
  app:
    build: .
    image: tinto_api:latest
    container_name: Tinto
    command: task dev
    volumes:
      - .:/tinto_api
    working_dir: /tinto_api
    ports:
      - "7777:7777" 
    environment:
      - TZ=America/Manaus
    env_file:
      - .env

  worker:
    image: tinto_api:latest
    container_name: Celery_tasks
    command: task worker
    volumes:
      - .:/tinto_api
    working_dir: /tinto_api
    ports:
      - "30059:30059"
    environment:
      - TZ=America/Manaus
    env_file:
      - .env
    depends_on:
      - app