services:
  nuxt_front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run preview
    network_mode: host